services:
  
  votes-write-application-1:
    build: .
    ports:
      - "8087:8087"
  
  votes-write-application-2:
    build: .
    ports:
      - "8088:8087"
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: INSIS2
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017